png('plot2.png')
data = read.table("household_power_consumption.txt", header = TRUE,sep = ";")
data = subset(data, Date == "1/2/2007" | Date == "2/2/2007")
data$Date = strptime(data$Date,"%d/%m/%y")
data$Date = as.Date(data$Date)
dev.off()