png('plot1.png')
data = read.table("household_power_consumption.txt", header = TRUE,sep = ";",na.strings="?", colClasses=c("character","character","numeric","numeric","numeric","numeric","numeric","numeric","numeric"))
data = subset(data, Date == "1/2/2007" | Date == "2/2/2007")
hist(data$Global_active_power,col = "red",xlab = "Global Active Power (kilowatts)", main = "Global Active Power")
dev.off()