png('plot3.png',width = 480, height = 480, units = "px")
data = read.table("household_power_consumption.txt", header = TRUE,sep = ";",na.strings="?", colClasses=c("character","character","numeric","numeric","numeric","numeric","numeric","numeric","numeric"))
data = subset(data, Date == "1/2/2007" | Date == "2/2/2007")
data$DateTime <- strptime(paste(data$Date, data$Time), "%d/%m/%Y %H:%M:%S")
plot(data$DateTime,data$Sub_metering_1,type= "l",xlab="", ylab="Energy sub metering")
lines(data$DateTime,data$Sub_metering_2,type= "l",col = "red")
lines(data$DateTime,data$Sub_metering_3,type= "l",col = "blue")
legend("topright", lty=1, lwd=1, col=c("black","blue","red"), legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.off()